In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as srn

In [32]:
df=pd.read_csv(r"C:\Users\Satish_Kundekar\Downloads\bangalore house price prediction.csv")

In [33]:
df

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.00,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.00,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.00,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.00,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.00,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3.0,2.0,325.00,2900.0,3,11206.896552,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
df.size

768960

In [35]:
df.shape

(7120, 108)

In [36]:
df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [37]:
df.isnull().sum()

bath                           0
balcony                        0
price                          0
total_sqft_int                 0
bhk                            0
                              ..
location_Hosur Road            0
location_Horamavu Banaswadi    0
location_Domlur                0
location_Mahadevpura           0
location_Tumkur Road           0
Length: 108, dtype: int64

In [38]:
df.duplicated().sum()

np.int64(467)

In [39]:
df.describe()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
count,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,...,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000,7120.000000
mean,2.390871,1.572759,96.454991,1479.729806,2.465169,5923.806855,0.750702,0.182303,0.061938,0.792697,...,0.003090,0.003090,0.002949,0.002949,0.002949,0.002949,0.002809,0.002809,0.002809,0.002809
std,0.876822,0.770583,116.185034,913.779769,0.841520,2556.650935,0.432637,0.386121,0.241060,0.405403,...,0.055505,0.055505,0.054232,0.054232,0.054232,0.054232,0.052929,0.052929,0.052929,0.052929
min,1.000000,0.000000,10.000000,350.000000,1.000000,1250.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,1.000000,49.230000,1100.000000,2.000000,4416.761042,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,2.000000,69.000000,1255.000000,2.000000,5417.855613,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.000000,2.000000,104.000000,1640.250000,3.000000,6618.285651,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,3.000000,2912.000000,30400.000000,9.000000,35000.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [40]:
df.info

<bound method DataFrame.info of       bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866
1      3.0      3.0  149.00          1750.0    3     8514.285714
2      3.0      2.0  150.00          1750.0    3     8571.428571
3      2.0      2.0   40.00          1250.0    2     3200.000000
4      2.0      2.0   83.00          1200.0    2     6916.666667
...    ...      ...     ...             ...  ...             ...
7115   3.0      2.0  325.00          2900.0    3    11206.896552
7116   3.0      1.0   84.83          1780.0    3     4765.730337
7117   2.0      1.0   48.00           880.0    2     5454.545455
7118   2.0      1.0   55.00          1000.0    2     5500.000000
7119   2.0      1.0   78.00          1400.0    3     5571.428571

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0
1                                 0                        1
2                                 1                        0
3                                 1                        0
4                                 0                        0
...                             ...                      ...
7115                              1                        0
7116                              1                        0
7117                              0                        0
7118                              0                        0
7119                              0                        0

      area_typePlot  Area  availability_Ready To Move  ...  \
0                       0                           1  ...
1                       0                           1  ...
2                       0                           1  ...
3                       0                           1  ...
4                       1                           1  ...
...                   ...                         ...  ...
7115                    0                           1  ...
7116                    0                           0  ...
7117                    1                           1  ...
7118                    1                           0  ...
7119                    1                           0  ...

      location_Kalena Agrahara  location_Horamavu Agara  \
0                            0                        0
1                            0                        0
2                            0                        0
3                            0                        0
4                            0                        0
...                        ...                      ...
7115                         0                        0
7116                         0                        0
7117                         0                        0
7118                         0                        0
7119                         0                        0

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0
1                           0                       0
2                           0                       0
3                           0                       0
4                           0                       0
...                       ...                     ...
7115                        0                       0
7116                        0                       0
7117                        0                       0
7118                        0                       0
7119                        0                       0

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0
1                             0                    0
2                             0                    0
3                             0                    0
4                             0                    0
...                         ...                  ...
7115                          0                    0
7116                          0                    0
7117                          0                    0
7118                          0                    0
7119                          0                    0

      location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                               0                0                     0
1                               0                0                     0
2                               0                0                     0
3                               0                0                     0
4                               0                0                     0
...                           ...              ...                   ...
7115                            0                0                     0
7116                            0                0                     0
7117                            0                0                     0
7118                            0                0                     0
7119                            0                0                     0

      location_Tumkur Road
0                        0
1                        0
2                        0
3                        0
4                        0
...                    ...
7115                     0
7116                     0
7117                     0
7118                     0
7119                     0

[7120 rows x 108 columns]>

In [41]:
df.drop_duplicates(inplace=True)

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.columns

Index(['bath', 'balcony', 'price', 'total_sqft_int', 'bhk', 'price_per_sqft',
       'area_typeSuper built-up  Area', 'area_typeBuilt-up  Area',
       'area_typePlot  Area', 'availability_Ready To Move',
       ...
       'location_Kalena Agrahara', 'location_Horamavu Agara',
       'location_Vidyaranyapura', 'location_BTM 2nd Stage',
       'location_Hebbal Kempapura', 'location_Hosur Road',
       'location_Horamavu Banaswadi', 'location_Domlur',
       'location_Mahadevpura', 'location_Tumkur Road'],
      dtype='str', length=108)

In [44]:
x=df.drop('price',axis=1) # X and Y Seprated Method
y=df['price']

In [45]:
x

,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,location_Whitefield,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.000000,1672.0,3,8971.291866,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.000000,1750.0,3,8514.285714,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.000000,1750.0,3,8571.428571,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.000000,1250.0,2,3200.000000,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.000000,1200.0,2,6916.666667,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7114,6.0,1.584376,3800.0,6,10263.157895,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7115,3.0,2.000000,2900.0,3,11206.896552,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.000000,1780.0,3,4765.730337,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.000000,880.0,2,5454.545455,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.000000,1400.0,3,5571.428571,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
y

0       150.00
1       149.00
2       150.00
3        40.00
4        83.00
         ...
7114    390.00
7115    325.00
7116     84.83
7117     48.00
7119     78.00
Name: price, Length: 6653, dtype: float64

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
sc=StandardScaler()

In [49]:
x_sc = sc.fit_transform(x)

In [53]:
from sklearn.model_selection import train_test_split

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x_sc, y, test_size=0.2, random_state=11)

In [58]:
x_sc_train = sc.fit_transform(x_train)
x_sc_test = sc.transform(x_test)

In [59]:
print(x_sc_train.shape)
print(x_sc_test.shape)

(5322, 107)
(1331, 107)

In [60]:
from sklearn.linear_model import LinearRegression

In [61]:
lr=LinearRegression()

In [62]:
lr.fit(x_sc_train,y_train)

LinearRegression()

In [63]:
lr.coef_ # m value

array([ 8.38104084e-01, -4.27555187e-01,  7.99040857e+01, -1.30928113e+01,
        6.69597559e+01, -2.49833442e-01, -1.74892888e+00, -4.41674716e+00,
       -2.36864279e+00, -3.54458830e+00, -2.55935767e+00,  7.28090021e-01,
       -1.06585695e+00,  1.93409777e+00, -4.55090843e-01, -1.49060089e+00,
       -3.24919599e-01,  2.47751849e+00, -1.70367572e+00,  2.61513428e+00,
       -3.00659488e+00, -1.55852501e+00, -1.01871073e+00, -1.20240416e-01,
        1.42867035e+00,  1.96152107e+00, -5.31918882e+00, -1.06962644e+00,
       -4.82924887e-01,  1.59507432e+00, -5.99324662e-01, -5.53046739e-01,
        8.39901980e-01, -1.55448281e+00,  7.11673086e-02, -1.50603663e+00,
        4.80223166e-01,  9.68131622e-01,  2.85963268e+00, -1.66217389e-01,
        5.35630866e-01,  6.22709118e-01, -2.13242976e-01,  1.35923564e+00,
       -1.60653809e+00, -3.56336577e+00, -7.31251104e-02,  8.29424252e-02,
       -6.59182288e-01, -1.92760962e+00, -1.13820530e+00,  7.74009627e-01,
        1.17850937e+00, -5.89590652e-01, -8.48507561e-01,  1.58875046e+00,
        2.14700586e+00, -2.13389994e-01, -2.58506028e+00, -1.03555650e+00,
        1.23106033e+00, -3.64306142e-01, -2.43164970e-01, -1.45453244e-01,
       -1.81200363e+00,  1.70882832e+00, -1.01901362e+00, -1.01479191e+00,
       -6.44185485e-01,  1.57217311e-02, -8.64151142e-01, -4.36391262e-01,
       -1.65821813e+00, -1.34158802e+00,  5.04878282e-01,  1.51890538e+00,
       -1.01169343e+00,  4.36553952e-01, -2.68887683e-01, -2.29710614e+00,
        7.20530743e-01,  1.23607505e-03,  2.36822366e-01,  3.45325547e+00,
        2.17348427e+00, -8.91923842e-01, -1.18937447e-01,  2.34547860e+00,
        5.22620104e-02,  6.76922491e-02,  2.02938817e-01,  1.42417681e+00,
        8.26430055e-01, -1.16950458e+00,  3.76570010e-01, -7.91399151e-01,
        1.56069335e+00,  3.70317999e-01,  1.26163851e+00,  7.18616080e-01,
       -5.49162831e-01, -1.56713293e+00, -7.91429727e-01,  8.38071457e-01,
       -2.11592141e+00,  3.83781621e-01, -4.63590838e-01])

In [64]:
lr.intercept_ # c value

np.float64(98.55547538519353)

In [68]:
lr.predict([x_sc_test[0]])

array([52.87720262])

In [69]:
lr.score(x_sc_train,y_train)

0.8499212732485733

In [70]:
y_pred=lr.predict(x_sc_test)

In [71]:
y_test

4802     50.855
3098    115.000
1619     69.000
1050     47.100
2561     85.000
         ...
6480     56.120
2205     66.000
6210    107.000
4393    120.000
3411     49.500
Name: price, Length: 1331, dtype: float64

In [72]:
result=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

In [73]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [75]:
mse=mean_squared_error(y_test,y_pred)

In [76]:
np.sqrt(mse)  #RMSE

np.float64(42.586917389549164)

In [78]:
r2_score(y_test,y_pred)

0.8766351617363192

In [79]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [80]:
mean_absolute_error(y_test,y_pred)

18.41434668781274

In [82]:
mean_squared_error(y_test,y_pred)

1813.6455327442848

In [83]:
np.sqrt(mse)

np.float64(42.586917389549164)

In [85]:
r2_score(y_test,y_pred)

0.8766351617363192